# Generated by Django 4.2.1 on 2023-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_filled',
            field=models.BooleanField(default=False),
        ),
    ]
