# Generated by Django 4.2.1 on 2023-05-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_full_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
