# Generated by Django 4.2.1 on 2023-05-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=55),
            preserve_default=False,
        ),
    ]
