# Generated by Django 4.2 on 2023-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profilepicture_alter_customuser_is_dealer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images\\profile_pictures'),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
