# Generated by Django 4.2 on 2023-05-29 00:18

import Users.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=enumfields.fields.EnumField(default='Male', enum=Users.models.Gender, max_length=10),
        ),
    ]
