# Generated by Django 4.2.1 on 2023-05-27 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='actual_delivery_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(choices=[('UPS', 'UPS'), ('FedEx', 'FedEx'), ('DHL', 'DHL'), ('Aramex', 'Aramex')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
