# Generated by Django 4.2 on 2023-05-14 10:26

import Payment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', enumfields.fields.EnumField(default='Credit Card', enum=Payment.models.PaymentType, max_length=11)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('expiration_month', models.CharField(blank=True, max_length=2)),
                ('expiration_year', models.CharField(blank=True, max_length=4)),
                ('cvv', models.CharField(blank=True, max_length=4)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
